[theme]

# Primary accent for interactive elements
primaryColor = '#f9bc60'

# Background color for the main content area
backgroundColor = '#abd1c6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#f9bc60'

# Color used for almost all text
textColor = '#e8e4e6'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
