[theme]

# Primary accent for interactive elements
primaryColor = '#ffd803'

# Background color for the main content area
backgroundColor = '#fffffe'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#bae8e8'

# Color used for almost all text
textColor = '#2d334a'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
